# Generated by Django 5.2 on 2025-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consortiumparticipation',
            name='drawn_client',
        ),
        migrations.AddField(
            model_name='consortium',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consortiumparticipation',
            name='draw_date',
            field=models.DateField(default=models.DateField(auto_now_add=True)),
        ),
    ]
