# Generated by Django 5.2 on 2025-05-21 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_of_measure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Consortium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='installments',
            new_name='installments_quantity',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='on_create',
            new_name='sale_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='metric',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.FloatField()),
                ('billing_date', models.DateField()),
                ('due_date', models.DateField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.capacity'),
        ),
        migrations.CreateModel(
            name='ConsortiumParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.user')),
                ('consortium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consortium')),
                ('drawn_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawn_participations', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=50)),
                ('discount', models.FloatField()),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.billing')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sale')),
            ],
        ),
    ]
