# Generated by Django 5.2 on 2025-07-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_consortiumparticipation_drawn_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldproduct',
            name='value',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
