# Generated by Django 5.2 on 2025-07-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_soldproduct_value_saleproduct_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleproduct',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
