# Generated by Django 5.2 on 2025-07-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_saleproduct_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sold_products',
            field=models.ManyToManyField(through='core.SoldProduct', to='core.product'),
        ),
    ]
